### ISSUE TITLE
Mount as a drive?

### ISSUE THREAD

**Issue by pbeart** [stewartmcgown/uds#45] opened 2019-05-15 19:55 UTC
So I've just stumbled on this and I'm wondering if you've considered adding a feature to mount the google docs filesystem as a drive? I understand this would be difficult for performance reasons as well as the significant amount of work that would be required to implement such a feature but I'm curious to see if you've considered anything like this.

**Comment by mvanaltvorst** [comment] 2019-05-16 21:45
duplicate of #40

**Closed** 2019-05-16 23:41 UTC
